FROM adoptopenjdk/openjdk8
MAINTAINER cutepanda123 panda@panda.com

COPY target/course-dubbo-service-1.0-SNAPSHOT.jar /course-dubbo-service.jar

ENTRYPOINT ["java", "-jar", "/course-dubbo-service.jar"]